### ISSUE TITLE
Border on the Ghost Buttons

### ISSUE THREAD

**Issue by oliviagrce** [oliviagrce/button-styles#1]
Hi @thomasjbradley,

My padding is near perfect on the primary, subtle and warning buttons. But because the border sits outside of the padding on the ghost buttons, it's pushing all of the other buttons down in the Markbot comparison screenshot. I've tried adding box-sizing: borderbox; but that doesn't work. It's also already at the top of the CSS main file under HTML. So I'm not sure how to get it to work. I'm also not allowed to put padding on the ghost button according to markbot. Any ideas?

<img width="400" alt="Screenshot 2019-11-09 at 14 33 34" src="https://user-images.githubusercontent.com/55007072/68534065-4e7d3a80-02fe-11ea-8ffa-b7f7a440482e.png">

**Comment by thomasjbradley** [comment]
You’ve adjusted the `padding` numbers to accommodate the screenshots—but stick to the original numbers in the Readme.

The trick is that *every button has a border*, just sometimes the border is the same colour as the background colour.

**Comment by oliviagrce** [comment]
Ok thanks @thomasjbradley 
I've made the changes but I've actually gone from 16% difference to 20% difference and I can't figure out where I've gone wrong. I've tried adjusting the div padding to see if that's it, but it doesn't seem like it.
<img width="400" alt="Screenshot 2019-11-09 at 14 33 34" src="https://user-images.githubusercontent.com/55007072/68534411-5c34bf00-0302-11ea-89b6-ed4f47447b5c.png">

**Comment by oliviagrce** [comment]
oops that's the wrong photo
@thomasjbradley 
<img width="400" alt="Screenshot 2019-11-09 at 15 04 08" src="https://user-images.githubusercontent.com/55007072/68534422-87b7a980-0302-11ea-8c03-7889d3cc934a.png">

**Comment by thomasjbradley** [comment]
I see you set the `border-style: hidden` it should be solid. We want to see the borders. But the `border-color` has to be set to match the button’s background colour.

**Comment by oliviagrce** [comment]
Awesome! thank you so much!
